# ./vendor/bin/ece-docker 'build:compose' --no-varnish --es-env-var='ES_JAVA_OPTS=-Xms512m' --es-env-var='ES_JAVA_OPTS=-Xmx512m' --host='magento.docker'
version: '2.1'
services:
  db:
    hostname: db.magento.docker
    image: 'mariadb:10.4'
    shm_size: 2gb
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - '3306'
    volumes:
      - '.:/app'
      - 'app-magento-db:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -pmagento2'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - db.magento.docker
  elasticsearch:
    hostname: elasticsearch.magento.docker
    image: 'magento/magento-cloud-docker-elasticsearch:7.11-1.3.2'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m
      - ES_JAVA_OPTS=-Xmx512m
    networks:
      magento:
        aliases:
          - elasticsearch.magento.docker
  fpm:
    hostname: fpm.magento.docker
    image: 'magento/magento-cloud-docker-php:8.1-fpm-1.3.2'
    env_file: ./.docker/config.env
    volumes:
      - '.:/app'
    networks:
      magento:
        aliases:
          - fpm.magento.docker
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MAGENTO_RUN_MODE=developer
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
  web:
    hostname: web.magento.docker
    image: 'magento/magento-cloud-docker-nginx:1.19-1.3.2'
    env_file: ./.docker/config.env
    volumes:
      - '.:/app'
    environment:
      - WITH_XDEBUG=0
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - FPM_PORT=9000
    networks:
      magento:
        aliases:
          - web.magento.docker
    depends_on:
      fpm:
        condition: service_started
  tls:
    hostname: tls.magento.docker
    image: 'magento/magento-cloud-docker-nginx:1.19-1.3.2'
    env_file: ./.docker/config.env
    networks:
      magento:
        aliases:
          - magento.docker
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - UPSTREAM_HOST=web
      - UPSTREAM_PORT=8080
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      web:
        condition: service_started
volumes:
  app-magento-db: {  }
networks:
  magento:
    driver: bridge
  magento-build:
    driver: bridge
